### ISSUE TITLE
Unavailable on maven central (or any other repository)

### ISSUE THREAD

**Issue by spockz** [rlazoti/finagle-metrics#1]
Can you publish this to a repository so we can use it directly instead of building it locally? Or are there any issues you are aware of why you don't want to share this?

**Comment by schrepfler** [comment]
+1 and please consider contributing to twitter commons metrics https://github.com/twitter/commons/issues/399

**Comment by schrepfler** [comment]
Btw, dumped the code in a Finatra server (not as jar) and managed to get it working. What's the procedure to register the metrics registry with a JmxReporter, I had to hack it and start it into the class as I couldn't find a guide to do so and the metrics seemed as internal to the MetricsStatsReceiver (it's not clear how you hook up reporters from the outside with the MSR).

**Comment by rlazoti** [comment]
@schrepfler to send metrics through JMX you need to use the JmxReporter, to do that just put the finagle-metrics jar into your project and add the following code to your codebase:

``` scala
val reporter: JmxReporter = JmxReporter.forRegistry(MetricsStatsReceiver.metrics).build()
reporter.start()
```

After that everything should work as expected. :wink:

**Comment by schrepfler** [comment]
Indeed it does :+1:  How expensive is this mapping between twitter metrics and dropwizard metrics, after the metrics are created are there there any listeners used under the cover to keep them updated or are they just overwritten all the time?

**Comment by rlazoti** [comment]
@spockz @schrepfler 

From now on, the finagle-metrics is available on oss sonatype.
The README is updated!

Thanks! :smile:
