### ISSUE TITLE
Duplicate gauge registration

### ISSUE THREAD

**Issue by ncreep** [rlazoti/finagle-metrics#11]
Hi,

I tried using `finagle-metrics` 0.10 along with Finagle 7.1.0 and I get bombarded with:
```
java.lang.IllegalArgumentException: A metric named clnt.some-client-name.connections already exists
        at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:91)
        at com.twitter.finagle.metrics.MetricsStatsReceiver$MetricGauge.<init>(MetricsStatsReceiver.scala:27)
        at com.twitter.finagle.metrics.MetricsStatsReceiver.addGauge(MetricsStatsReceiver.scala:51)
        at com.twitter.finagle.stats.BroadcastStatsReceiver$Two$$anon$1.<init>(BroadcastStatsReceiver.scala:29)
...
```

I was unable to reproduce this locally, but it happens all the time on a server with real traffic. Probably because the problem requires many concurrent requests to become manifest.

My suspicions fall on [this](https://github.com/rlazoti/finagle-metrics/blob/a3521d665af6d092cd66d127134541be8c993f4d/src/main/scala/com/twitter/finagle/metrics/MetricsStatsReceiver.scala#L19) block of code. Although the calls inside the `MetricGauge` are synchronized, the calls to [`addGauge`](https://github.com/rlazoti/finagle-metrics/blob/a3521d665af6d092cd66d127134541be8c993f4d/src/main/scala/com/twitter/finagle/metrics/MetricsStatsReceiver.scala#L50) are not. 

Can it be that multiple clients are calling `addGauge` all at once and each manages to invoke `metrics.register` independently?

**Comment by ncreep** [comment]
Actually, I now see that there's an open pull request (#12) that should take care of this issue.
Is it possible to merge it and have releases both for Finagle 7.x and 6.x?

**Comment by rlazoti** [comment]
@ncreep Sure thing, but have you tested this pull request #12 to be sure that this issue was fixed?
Just let me know if you need an snapshot version containing this PR to test it. 😉

**Comment by ncreep** [comment]
I tested #12 against `0.9` and it seems to have fixed another issue that I used to have (which is probably similar, but more subtle since it doesn't throw any exceptions). So that fix is worthwhile anyway.

As to re-creating the original issue described, it'll take me a bit more time to do that. I can publish my own local snapshot, so no need to do anything special. Will report back once I do.

**Comment by ncreep** [comment]
I now tested against `0.10` and the original issue seems to be gone (it's a bit hard to tell, since it's not deterministic).

**Comment by rlazoti** [comment]
@ncreep Thank you for testing it. :)
There's a new release 0.0.12 that includes the PR #12.

**Comment by ncreep** [comment]
Great, thanks
