### ISSUE TITLE
Update dependency versions

### ISSUE THREAD

**Issue by pmatpadi** [rlazoti/finagle-metrics#15]
Hi, I would like to update the versions of finagle and dropwizard metrics, so I can continue using this library in my project. I have created https://github.com/rlazoti/finagle-metrics/pull/14. It compiles fine locally, however Travis CI is failing https://travis-ci.org/github/rlazoti/finagle-metrics/builds/669016934?utm_source=github_status&utm_medium=notification 

Could you please help resolve this, and merge my PR if you approve?
Thanks

**Comment by rlazoti** [comment]
Thanks for your PR. 👍 
I just released a new version 0.0.13 with your changes.
