### ISSUE TITLE
finagle v6.35: HttpClient:  IllegalArgumentException: A metric named inet.dns.queue_size already exists

### ISSUE THREAD

**Issue by mahilee** [rlazoti/finagle-metrics#2]
Http Client runtime exception thrown at startup under finagle v6.35: 
e.g. 

Http.newService("172.18.10.98:9191")

results in IllegalArgumentException: A metric named inet.dns.queue_size already exists

oOo
sbt dependancies:

scalaVersion := "2.11.8"

val finagleVersion = "6.35.0"

libraryDependencies ++=
  Seq("com.twitter" %% "finagle-core" ,
    "com.twitter" %% "finagle-http" ).map(_ % finagleVersion withSources())

libraryDependencies ++= Seq("com.github.rlazoti" % "finagle-metrics_2.11" % "0.0.2")

**Comment by Grogs** [comment]
I hit this issue too, for all gauges, for all metric names. Finagle seems to call `addGauge` every time to interact with it. If you look at the scaladoc for finagle's `StatsReceiver.addGauge` then it mentions that finagle will only hold a weak reference...

Our solution/workaround was to keep put a ConcurrentHashMap of gauges into our implemention of the StatsReceived, then do a `.putIfAbsent` of the respective gauge, so we only create the gauge once per metric.

**Comment by rlazoti** [comment]
@mahilee @Grogs 

Guys, thanks for reporting this issue.

I fixed it, so please update finagle-metrics to version **0.0.3** and let me know if you find out any other issue. :+1:
