### ISSUE TITLE
Potential data race in MetricsGauge

### ISSUE THREAD

**Issue by taion809** [rlazoti/finagle-metrics#5]
Hello,
I see that a similar issue had been logged in issue #2, the fix for which was to remove matching gauges prior to adding a new value.  This seems to work in the general case but I've run into an issue where occassionally we'll see an issue such as `A metric named clnt.some_label.queue_size already exists`.  Especially when using Future.join or Future.collect which leads me to believe there is a data race between when the metric is checked and when it is actually written.  I forked the repository and wrapped the [call](https://github.com/rlazoti/finagle-metrics/blob/master/src/main/scala/com/twitter/finagle/metrics/MetricsStatsReceiver.scala#L17) with `this.synchronized{}` which appears to have fixed my own issue.

**Comment by taion809** [comment]
I was wrong :\

**Comment by rlazoti** [comment]
Hi @taion809,
did you fixed it or are you still having this issue?

**Comment by taion809** [comment]
Sorry I ended up changing teams so I haven't been working with finagle much
so for me this is no longer an issue but it was a problem with finatra :/

**Comment by taion809** [comment]
Forgot to mention I ended up forking he project and wrapping it in a try
